[package]
name = "balance"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.10.0"
solana-client = "1.10.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"